apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-orders
  labels:
    app: fastapi-orders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-orders
  template:
    metadata:
      labels:
        app: fastapi-orders
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: fastapi-orders
          image: aagash11/fastapi-orders:6f63bdcd
          ports:
            - containerPort: 8000
          env:
            - name: ENABLE_LOKI
              value: "true"
            - name: LOKI_URL
              value: "http://loki:3100/loki/api/v1/push"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
